/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlycuahanggiay_java.GUI;

import java.awt.CardLayout;
import quanlycuahanggiay_java.BUS.GiayBUS;
import quanlycuahanggiay_java.DTO.PhieuNhap;
import quanlycuahanggiay_java.DTO.XuatXu;
import quanlycuahanggiay_java.DTO.ThuongHieu;
import quanlycuahanggiay_java.DTO.Giay;
import quanlycuahanggiay_java.DTO.Loai;
import quanlycuahanggiay_java.DTO.MauSac;
import quanlycuahanggiay_java.DAO.XuatXuDAO;
import quanlycuahanggiay_java.DAO.ThuongHieuDAO;
import quanlycuahanggiay_java.DAO.LoaiDAO;
import quanlycuahanggiay_java.DAO.MauSacDAO;
import quanlycuahanggiay_java.DAO.GiayDAO;
import quanlycuahanggiay_java.DAO.PhieuNhapDAO;

import quanlycuahanggiay_java.BUS.XuatXuBUS;
import quanlycuahanggiay_java.BUS.ThuongHieuBUS;
import quanlycuahanggiay_java.BUS.LoaiBUS;
import quanlycuahanggiay_java.BUS.MauSacBUS;
import quanlycuahanggiay_java.BUS.GiayBUS;
import quanlycuahanggiay_java.DTO.ChiTietPhieuNhap;
import quanlycuahanggiay_java.BUS.GiayBUS;
import quanlycuahanggiay_java.BUS.ChiTietPNBUS;
import quanlycuahanggiay_java.BUS.KhachHangBUS;
import quanlycuahanggiay_java.DAO.ChiTietPNDAO;
import java.util.ArrayList;
import java.math.BigDecimal;
import java.util.Date;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.time.LocalDateTime;
import java.sql.ResultSet;
import javax.swing.SwingUtilities;
import quanlycuahanggiay_java.DAO.ConnectUnit;

/**
 *
 * @author Admin
 */
public class FormNhapHang_panel extends javax.swing.JPanel {

    ArrayList<Giay> list;
    ArrayList<ChiTietPhieuNhap> chiTietPN;

    /**
     * Creates new form FormNhapHang_panel
     */
    public FormNhapHang_panel() {
        list = new ArrayList<>();
        chiTietPN = new ArrayList<>();
        Memory.tongTien.clear();
        initComponents();
        ShowMaMau();
        ShowMaTH();
        ShowMaXX();
        ShowMaLoai();
        ShowMaNCC();
    }

    private void ShowMaLoai() {
        ConnectUnit conn = new ConnectUnit();
        try {
            ResultSet rs = conn.Select("LOAI");
            MaLoai.removeAllItems();
            while (rs.next()) {
                String maLoai = rs.getString("MALOAI");
                MaLoai.addItem(maLoai);
            }
            conn.Close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ShowMaNCC() {
        ConnectUnit conn = new ConnectUnit();
        try {
            ResultSet rs = conn.Select("NHACUNGCAP");
            MaNCC.removeAllItems();
            while (rs.next()) {
                String maLoai = rs.getString("MANCC");
                MaNCC.addItem(maLoai);
            }
            conn.Close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ShowMaXX() {
        ConnectUnit conn = new ConnectUnit();
        try {
            ResultSet rs = conn.Select("XUATXU");
            MaXX.removeAllItems();
            while (rs.next()) {
                String maLoai = rs.getString("MAXX");
                MaXX.addItem(maLoai);
            }
            conn.Close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ShowMaMau() {
        ConnectUnit conn = new ConnectUnit();
        try {
            ResultSet rs = conn.Select("MAUSAC");
            MaMau.removeAllItems();
            while (rs.next()) {
                String maLoai = rs.getString("MAMAU");
                MaMau.addItem(maLoai);
            }
            conn.Close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ShowMaTH() {
        ConnectUnit conn = new ConnectUnit();
        try {
            ResultSet rs = conn.Select("THUONGHIEU");
            MaThuongHieu.removeAllItems();
            while (rs.next()) {
                String maLoai = rs.getString("MATHUONGHIEU");
                MaThuongHieu.addItem(maLoai);
            }
            conn.Close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_panel = new javax.swing.JPanel();
        Size = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        Nam = new javax.swing.JCheckBox();
        Nu = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        ChatLieu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        MaLoai = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        MaXX = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        MaMau = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        TenGiay = new javax.swing.JTextField();
        MaThuongHieu = new javax.swing.JComboBox<>();
        SoLuong = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        MaNCC = new javax.swing.JComboBox<>();
        delete = new javax.swing.JButton();
        NhapHang = new javax.swing.JButton();
        DonGia = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ChiTiet = new javax.swing.JTable();

        body_panel.setBackground(new java.awt.Color(250, 243, 224));
        body_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(169, 169, 169)));

        Size.setBackground(new java.awt.Color(51, 255, 204));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("Đối tượng sử dụng");

        Nam.setText("Nam");

        Nu.setText("Nữ");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("Chất liệu");

        ChatLieu.setBackground(new java.awt.Color(51, 255, 204));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("THÔNG TIN SẢN PHẨM");

        MaLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        MaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaLoaiActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Mã loại");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Mã xuất xứ");

        MaXX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Mã màu");

        MaMau.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Mã thương hiệu");

        TenGiay.setBackground(new java.awt.Color(51, 255, 204));
        TenGiay.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        MaThuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Mã nhà cung cấp");

        add.setBackground(new java.awt.Color(102, 255, 204));
        add.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setText("Thêm");
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        MaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        delete.setBackground(new java.awt.Color(51, 255, 204));
        delete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setText("Xóa");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });

        NhapHang.setBackground(new java.awt.Color(153, 255, 153));
        NhapHang.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        NhapHang.setForeground(new java.awt.Color(0, 0, 0));
        NhapHang.setText("NHẬP HÀNG");
        NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhapHangMouseClicked(evt);
            }
        });
        NhapHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NhapHangActionPerformed(evt);
            }
        });

        DonGia.setBackground(new java.awt.Color(51, 255, 204));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Tên giày*");

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Số lượng*");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Giá bán");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Size");

        ChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên giày", "Số lượng", "Giá nhập"
            }
        ));
        ChiTiet.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ChiTietComponentShown(evt);
            }
        });
        jScrollPane2.setViewportView(ChiTiet);

        javax.swing.GroupLayout body_panelLayout = new javax.swing.GroupLayout(body_panel);
        body_panel.setLayout(body_panelLayout);
        body_panelLayout.setHorizontalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 664, Short.MAX_VALUE)
                        .addComponent(NhapHang))
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TenGiay, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DonGia, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SoLuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(body_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(body_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(body_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(24, 24, 24)
                                        .addComponent(Nam)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Nu))
                                    .addGroup(body_panelLayout.createSequentialGroup()
                                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel26)
                                            .addComponent(jLabel27))
                                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(body_panelLayout.createSequentialGroup()
                                                .addGap(78, 78, 78)
                                                .addComponent(ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_panelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(MaLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(body_panelLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(add)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        body_panelLayout.setVerticalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TenGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(delete)
                            .addComponent(add)))
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_panelLayout.createSequentialGroup()
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel28)
                                    .addComponent(MaMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(MaThuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_panelLayout.createSequentialGroup()
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Nam)
                                    .addComponent(Nu))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ChatLieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25))))
                        .addGap(14, 14, 14)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(MaXX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaLoaiActionPerformed
        
    }//GEN-LAST:event_MaLoaiActionPerformed

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked

    }//GEN-LAST:event_addMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (TenGiay.getText().isEmpty() || DonGia.getText().isEmpty() || Size.getText().isEmpty() || (!Nam.isSelected() && !Nu.isSelected()) || ChatLieu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Giay e = new Giay();
        ChiTietPhieuNhap ctpn = new ChiTietPhieuNhap();
        e.setStrTenGiay(TenGiay.getText());
        BigDecimal giaBan = new BigDecimal(DonGia.getText());

        e.setiSoLuong((int) SoLuong.getValue());
        BigDecimal soLuong = new BigDecimal((int) SoLuong.getValue());
        Memory.giaban = giaBan.multiply(soLuong);
        e.setiGia(Memory.giaban);
        if (e.getiSoLuong() <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống", "Thông báo", JOptionPane.WARNING_MESSAGE);
            SoLuong.setValue(0);
            SoLuong.requestFocus();
            return;
        }
        e.setiSize(Integer.parseInt(Size.getText()));
        if (Nam.isSelected()) {
            e.setStrDoiTuongSD(true);
        }
        if (Nu.isSelected()) {
            e.setStrDoiTuongSD(false);
        }
        e.setStrChatLieu(ChatLieu.getText());
        Object selectedObject = MaLoai.getSelectedItem();
        String maloai = (String) selectedObject;
        e.getLoai().setMaLoai(maloai);

        Object mxx = MaXX.getSelectedItem();
        String Maxx = (String) mxx;
        e.getXx().setStrMaxuatxu(Maxx);

        Object mamau = MaMau.getSelectedItem();
        String maMau = (String) mamau;
        e.getMausac().setMaMau(maMau);

        Object mth = MaThuongHieu.getSelectedItem();
        String maThuongHieu = (String) mth;
        e.getThuonghieu().setMaThuongHieu(maThuongHieu);

        // add chi tiet PN
        ctpn.setGiaNhap(Memory.giaban);
        ctpn.getGiay().setStrMaGiay(0); // luc nhap hang se cap nhat lai ma giay
        ctpn.getPn().setMaPN(0);    // luc nhap hang se cap nhat lai ma PN
        ctpn.getGiay().setiSoLuong((int) SoLuong.getValue());

        chiTietPN.add(ctpn);
        list.add(e);
        try {
            DefaultTableModel model = (DefaultTableModel) ChiTiet.getModel();
            Object[] rowData = {e.getStrTenGiay(), e.getiSoLuong(), e.getiGia()};
            model.addRow(rowData);
            Memory.tongTien.add(Memory.giaban);
              
        } catch (Exception ex) {
            System.out.println("Lỗi xảy ra: " + ex.getMessage());
        }
        
        TenGiay.setText("");
        SoLuong.setValue(0);
        DonGia.setText("");
        Size.setText("");
        ChatLieu.setText("");
        TenGiay.requestFocus();
    }//GEN-LAST:event_addActionPerformed

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        try {
            int rowIndex = ChiTiet.getSelectedRow();
            if (rowIndex != -1) {
                DefaultTableModel model = (DefaultTableModel) ChiTiet.getModel();
                model.removeRow(rowIndex);
                list.remove(rowIndex);
                chiTietPN.remove(rowIndex);
                Memory.tongTien.remove(rowIndex);
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn một dòng để xóa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_deleteMouseClicked

    private void NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhapHangMouseClicked

        try {
            PhieuNhap pn = new PhieuNhap();

            ConnectUnit conn = new ConnectUnit();
            PhieuNhapDAO pnDAO = new PhieuNhapDAO();
            ChiTietPNDAO chiTietPNDAO = new ChiTietPNDAO();
            GiayBUS giayBUS = new GiayBUS();
            GiayDAO giayDAO = new GiayDAO();

            //them phieu nhap vao db
            LocalDateTime ngayHienTai = LocalDateTime.now();
            java.sql.Date sqlDate = java.sql.Date.valueOf(ngayHienTai.toLocalDate());
            pn.setNgayNhap(sqlDate);
            pn.getNv().setMaNV(Memory.nhanvien.getMaNV());
            Object selectedObject = MaNCC.getSelectedItem();
            String mancc = (String) selectedObject;
            pn.getNCC().setMaNCC(mancc);
            BigDecimal sum = BigDecimal.ZERO; // Khởi tạo tổng ban đầu là 0
            for (BigDecimal value : Memory.tongTien) {
                sum = sum.add(value); // Cộng giá trị hiện tại vào tổng
            }
            pn.setTongTien(sum);

            if (pnDAO.them(pn)) {
                System.out.println("ok");
            } else {
                System.out.println("no");
            }

            //them chi tiet phieu nhap vao db
            for (int i = 0; i < list.size(); i++) {
                Giay giay = list.get(i);
                ChiTietPhieuNhap ct = chiTietPN.get(i);

                // Thực hiện xử lý với mỗi phần tử trong danh sách
                if (giayDAO.them(giay)) {
                    System.out.println("Thêm giày thành công");
                } else {
                    System.out.println("Không thể thêm giày");
                }

                // Gán mã giày cho chi tiết phiếu nhập
                ct.getGiay().setStrMaGiay(conn.getMaxMaGiay());
                ct.getPn().setMaPN(conn.getMaxMaPN());
                if (chiTietPNDAO.them(ct)) {
                    System.out.println("ok");
                } else {
                    System.out.println("no");
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());

        } finally {
            MainFrame1 mf = (MainFrame1) SwingUtilities.getWindowAncestor(this);

            // Tạo panel mới HoaDonGUI_panel
            NhapHang_panel hdp = new NhapHang_panel();

            // Thêm panel mới vào Body_panel của MainFrame1
            mf.getBody_panel().add(hdp, "NhapHang_panel");

            // Sử dụng CardLayout để chuyển đến HoaDonGUI_panel
            CardLayout cl = (CardLayout) (mf.getBody_panel().getLayout());
            cl.show(mf.getBody_panel(), "NhapHang_panel");

            // Cập nhật giao diện người dùng
            mf.getBody_panel().revalidate();
            mf.getBody_panel().repaint();
        }
    }//GEN-LAST:event_NhapHangMouseClicked

    private void NhapHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NhapHangActionPerformed

    }//GEN-LAST:event_NhapHangActionPerformed

    private void ChiTietComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ChiTietComponentShown

    }//GEN-LAST:event_ChiTietComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ChatLieu;
    private javax.swing.JTable ChiTiet;
    private javax.swing.JTextField DonGia;
    private javax.swing.JComboBox<String> MaLoai;
    private javax.swing.JComboBox<String> MaMau;
    private javax.swing.JComboBox<String> MaNCC;
    private javax.swing.JComboBox<String> MaThuongHieu;
    private javax.swing.JComboBox<String> MaXX;
    private javax.swing.JCheckBox Nam;
    private javax.swing.JButton NhapHang;
    private javax.swing.JCheckBox Nu;
    private javax.swing.JTextField Size;
    private javax.swing.JSpinner SoLuong;
    private javax.swing.JTextField TenGiay;
    private javax.swing.JButton add;
    private javax.swing.JPanel body_panel;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
