/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlycuahanggiay_java.GUI;
import java.io.FileOutputStream;
import java.io.IOException;
import java.math.BigDecimal;
import quanlycuahanggiay_java.DAO.ConnectUnit;
import quanlycuahanggiay_java.DAO.GiayDAO;
import quanlycuahanggiay_java.BUS.GiayBUS;
import quanlycuahanggiay_java.DTO.Giay;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
/**
 *
 * @author Admin
 */
public class HangHoa_panel extends javax.swing.JPanel {

    /**
     * Creates new form HangHoa_panel
     */
    public HangHoa_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_panel = new javax.swing.JPanel();
        tengiay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        magiay = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        chiTietGiay = new javax.swing.JTable();
        excel = new javax.swing.JButton();

        body_panel.setBackground(new java.awt.Color(250, 243, 224));
        body_panel.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(169, 169, 169)));

        tengiay.setBackground(new java.awt.Color(51, 255, 204));
        tengiay.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tengiay.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nhập tên");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nhập mã giày");

        magiay.setBackground(new java.awt.Color(51, 255, 204));
        magiay.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        magiay.setForeground(new java.awt.Color(0, 0, 0));

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("TÌM KIẾM");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        chiTietGiay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên giày", "Số lượng", "Giá nhập"
            }
        ));
        chiTietGiay.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                chiTietGiayComponentShown(evt);
            }
        });
        jScrollPane5.setViewportView(chiTietGiay);

        excel.setBackground(new java.awt.Color(153, 255, 153));
        excel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        excel.setForeground(new java.awt.Color(0, 0, 0));
        excel.setText("XUẤT EXCEL");
        excel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                excelMouseClicked(evt);
            }
        });
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body_panelLayout = new javax.swing.GroupLayout(body_panel);
        body_panel.setLayout(body_panelLayout);
        body_panelLayout.setHorizontalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGap(891, 891, 891)
                        .addComponent(excel, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(jLabel11))
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(tengiay, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(magiay, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 255, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        body_panelLayout.setVerticalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(excel)
                .addGap(31, 31, 31)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addComponent(magiay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1))
                    .addComponent(tengiay, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(body_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(body_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String[] arr = {"Mã Giày", "Tên Giày", "Số Lượng", "Giá", "Size", "Đối Tượng SD", "Chất Liệu", "Mã Loại", "Mã Xuất Xứ", "Mã Màu", "Mã Thương Hiệu"};
        DefaultTableModel model = new DefaultTableModel(arr, 0);
        try {

            GiayBUS giayBUS = new GiayBUS();
            if (!tengiay.getText().isEmpty() && !magiay.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng chỉ nhập 1 trong 2 ô!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                magiay.setText("");
                tengiay.setText("");
            } else if (!tengiay.getText().isEmpty()) {
                for (Giay g : giayBUS.timKiem_TenGiay(tengiay.getText())) {
                    String maGiay = String.valueOf(g.getStrMaGiay());
                    String sl = String.valueOf(g.getiSoLuong());
                    String gia = String.valueOf(g.getiGia());
                    String size = String.valueOf(g.getiSize());
                    String gt;

                    if (g.isStrDoiTuongSD()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    String[] rowData = {maGiay, g.getStrTenGiay(), sl, gia, size, gt, g.getStrChatLieu(), g.getLoai().getMaLoai(), g.getXx().getStrMaxuatxu(), g.getMausac().getMaMau(), g.getThuonghieu().getMaThuongHieu()};

                    model.addRow(rowData);
                }
            } else if (!magiay.getText().isEmpty()) {
                Giay g = new Giay();
                g = giayBUS.timKiem_MaGiay(Integer.parseInt(magiay.getText()));
                if (g != null) {
                    String maGiay = String.valueOf(g.getStrMaGiay());
                    String sl = String.valueOf(g.getiSoLuong());
                    String gia = String.valueOf(g.getiGia());
                    String size = String.valueOf(g.getiSize());
                    String gt;

                    if (g.isStrDoiTuongSD()) {
                        gt = "Nam";
                    } else {
                        gt = "Nu";
                    }

                    String[] rowData = {maGiay, g.getStrTenGiay(), sl, gia, size, gt, g.getStrChatLieu(), g.getLoai().getMaLoai(), g.getXx().getStrMaxuatxu(), g.getMausac().getMaMau(), g.getThuonghieu().getMaThuongHieu()};

                    model.addRow(rowData);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Không được để trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);

            }

        } catch (Exception e) {
        }

        chiTietGiay.setModel(model);

    }//GEN-LAST:event_jButton1MouseClicked

    private void chiTietGiayComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_chiTietGiayComponentShown

    }//GEN-LAST:event_chiTietGiayComponentShown

    private void excelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_excelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_excelMouseClicked

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        exportToExcel();
    }//GEN-LAST:event_excelActionPerformed
  private void exportToExcel() {
        Workbook workbook = new XSSFWorkbook();
        Sheet sheet1 = workbook.createSheet("HOADON");

        // Xuất dữ liệu từ ChiTietHD
        TableModel model1 = chiTietGiay.getModel();
        Row headerRow1 = sheet1.createRow(0);
        for (int i = 0; i < model1.getColumnCount(); i++) {
            headerRow1.createCell(i).setCellValue(model1.getColumnName(i));
        }

        for (int i = 0; i < model1.getRowCount(); i++) {
            Row row = sheet1.createRow(i + 1);
            for (int j = 0; j < model1.getColumnCount(); j++) {
                row.createCell(j).setCellValue(String.valueOf(model1.getValueAt(i, j)));
            }
        }

      

        // Đường dẫn lưu file
        String filePath = "D:/Users/Admin/Documents/NetBeansProjects/QuanLyCuaHangGiay_Java/src/quanlycuahanggiay_java/excel/giay.xlsx";
        try (FileOutputStream fileOut = new FileOutputStream(filePath)) {
            workbook.write(fileOut);
            workbook.close();
            JOptionPane.showMessageDialog(this, "Export successful to " + filePath);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error exporting file: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body_panel;
    private javax.swing.JTable chiTietGiay;
    private javax.swing.JButton excel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField magiay;
    private javax.swing.JTextField tengiay;
    // End of variables declaration//GEN-END:variables
}
