/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycuahanggiay_java.GUI;

import quanlycuahanggiay_java.DTO.NhanVien;
import quanlycuahanggiay_java.DTO.TaiKhoangNV;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    TaiKhoangNV nv = null;
    NhanVien nvBUS = null;

    
    public Home(TaiKhoangNV tk, NhanVien nvB) {
        try {
        nv = new TaiKhoangNV();
        nvBUS = new NhanVien(); 
    } catch(Exception ex) {
        ex.printStackTrace(); 
    }
         nv.setMaNV(tk.getMaNV());
        nv.setMatKhau(tk.getMatKhau());
        nv.setCapBac(tk.getCapBac());
        nvBUS = nvB;
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ShowName = new javax.swing.JLabel(nvBUS.getHo() + " " + nvBUS.getTen());
        jLabel7 = new javax.swing.JLabel();
        ShowLevel = new javax.swing.JLabel(nvBUS.getChucVu());
        Logout = new javax.swing.JLabel();
        ShowID = new javax.swing.JLabel(String.valueOf(nv.getMaNV()));
        jPanel9 = new javax.swing.JPanel();
        HoaDon = new javax.swing.JLabel();
        XuatExcel = new javax.swing.JLabel();
        HangHoa = new javax.swing.JLabel();
        ThongKe = new javax.swing.JLabel();
        NhapHang = new javax.swing.JLabel();
        KhuyenMai = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 102, 255));
        jLabel1.setForeground(new java.awt.Color(153, 102, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/boy 1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 126, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 13, 21, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Họ Và Tên:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 56, 79, 23));

        ShowName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ShowName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ShowName, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 51, -1, 32));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Chức vụ:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 13, -1, -1));

        ShowLevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ShowLevel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(ShowLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/Logout (1).png"))); // NOI18N
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        jPanel1.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 70, 70));
        jPanel1.add(ShowID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 15, 70, 20));

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/bill.png"))); // NOI18N
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);
            }
        });

        XuatExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/excel.png"))); // NOI18N
        XuatExcel.setText("jLabel4");
        XuatExcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XuatExcelMouseClicked(evt);
            }
        });

        HangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/goods.png"))); // NOI18N
        HangHoa.setText("jLabel4");
        HangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HangHoaMouseClicked(evt);
            }
        });

        ThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/statis.png"))); // NOI18N
        ThongKe.setText("jLabel4");
        ThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ThongKeMouseClicked(evt);
            }
        });

        NhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/import.png"))); // NOI18N
        NhapHang.setText("jLabel4");
        NhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhapHangMouseClicked(evt);
            }
        });

        KhuyenMai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlycuahanggiay_java/images/currency.png"))); // NOI18N
        KhuyenMai.setText("jLabel4");
        KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KhuyenMaiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(HangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(XuatExcel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(XuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseClicked

        try {

            HoaDonGUI hd = new HoaDonGUI();
            hd.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi " + e.getMessage());
        }
    }//GEN-LAST:event_HoaDonMouseClicked

    private void KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KhuyenMaiMouseClicked
        try {

            KhuyenMai km = new KhuyenMai();
            km.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi " + e.getMessage());
        }    }//GEN-LAST:event_KhuyenMaiMouseClicked

    private void XuatExcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XuatExcelMouseClicked
        try {

            XuatExcel XE = new XuatExcel();
            XE.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi " + e.getMessage());
        }    }//GEN-LAST:event_XuatExcelMouseClicked

    private void HangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HangHoaMouseClicked
        try {

            HangHoa hh = new HangHoa();
            hh.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi " + e.getMessage());
        }
    }//GEN-LAST:event_HangHoaMouseClicked

    private void NhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhapHangMouseClicked
        try {

            NhapHang nh = new NhapHang();
            nh.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi " + e.getMessage());
        }
    }//GEN-LAST:event_NhapHangMouseClicked

    private void ThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ThongKeMouseClicked
        try {

            ThongKe tk = new ThongKe();
            tk.setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            System.out.println("Lỗi " + e.getMessage());
        }
    }//GEN-LAST:event_ThongKeMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Xác nhận đăng xuất", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                LoginForm login = new LoginForm();
                login.setVisible(true);
                this.setVisible(false);
            } catch (Exception e) {
                System.out.println("Lỗi " + e.getMessage());
            }
        }
    }//GEN-LAST:event_LogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HangHoa;
    private javax.swing.JLabel HoaDon;
    private javax.swing.JLabel KhuyenMai;
    private javax.swing.JLabel Logout;
    private javax.swing.JLabel NhapHang;
    private javax.swing.JLabel ShowID;
    private javax.swing.JLabel ShowLevel;
    private javax.swing.JLabel ShowName;
    private javax.swing.JLabel ThongKe;
    private javax.swing.JLabel XuatExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables

}
